Initialized IDT
ParadiseOS/ParadiseOS pull request #7
Opened 2024-04-03 06:00 UTC by lk1422

# Pull Request

## Description

Please include a summary of the changes and the related issue (if applicable). Please also include relevant motivation and context. List any dependencies that are required for this change (if applicable).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

Try to checkoff as much as possible if not everything!

2024-04-04 04:26 UTC, Tripplenut requested changes
fix comment

2024-04-04 04:26 UTC, Tripplenut commented on src/boot.s
> +    mov eax, [esp+0x4]; get GDT address
...

2024-04-08 00:02 UTC, joyal-mathew approved these changes

2024-04-08 00:03 UTC, Tripplenut approved these changes
lgtm

2024-04-08 00:03 UTC, merged